# DVF data exploration
# Author: Xavier VAN AUSLOOS, 9/02/26
# Notebook for preparing dataset with all mutations in France for houses only
# DVF Data from 2020 to 2025

In [17]:
from pathlib import Path
import sys

# Ensure project src is on path (kernel cwd is often the notebook dir, not project root)
_project_root = Path.cwd() if (Path.cwd() / "src" / "dvf").exists() else Path.cwd().parent
_src = _project_root / "src"
if _src.exists() and str(_src) not in sys.path:
    sys.path.insert(0, str(_src))

from dvf import load_dvf_raw, load_dvf_csv, load_dvf_plus, summarize_mutations

In [18]:
# Data directory and list all files
_project_root = Path.cwd() if (Path.cwd() / "src" / "dvf").exists() else Path.cwd().parent
raw_dir = _project_root / "data" / "raw"
all_files = sorted(raw_dir.glob("*"))
txt_files = sorted(raw_dir.glob("*.txt"))
print("All files in data/raw:", [f.name for f in all_files if not f.name.startswith(".")])
print(" .txt files (will be loaded):", [f.name for f in txt_files])

All files in data/raw: ['ValeursFoncieres-2020-S2.txt', 'ValeursFoncieres-2021.txt', 'ValeursFoncieres-2022.txt', 'ValeursFoncieres-2023.txt', 'ValeursFoncieres-2024.txt', 'ValeursFoncieres-2025-S1.txt', 'zip']
 .txt files (will be loaded): ['ValeursFoncieres-2020-S2.txt', 'ValeursFoncieres-2021.txt', 'ValeursFoncieres-2022.txt', 'ValeursFoncieres-2023.txt', 'ValeursFoncieres-2024.txt', 'ValeursFoncieres-2025-S1.txt']

In [19]:
# Load all .txt files from raw (pipe-separated), concatenate into one DataFrame
import pandas as pd

if not txt_files:
    df = pd.DataFrame()
    print("No .txt files in data/raw.")
else:
    frames = []
    for p in txt_files:
        print(f"Loading {p.name}...")
        frames.append(load_dvf_raw(p, sep="|"))
    df = pd.concat(frames, ignore_index=True)
    print(f"Total rows: {len(df):,}")
df.head()

Loading ValeursFoncieres-2020-S2.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code voie, 1: Code departement, 2: No Volume, 3: 1er lot, 4: 2eme lot, 5: 3eme lot, 6: Surface Carrez du 4eme lot, 7: Surface Carrez du 5eme lot, 8: Nature culture speciale) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Loading ValeursFoncieres-2021.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code departement, 1: No Volume, 2: 1er lot, 3: 2eme lot, 4: 3eme lot, 5: Surface Carrez du 3eme lot, 6: 4eme lot, 7: Surface Carrez du 4eme lot, 8: Surface Carrez du 5eme lot, 9: Nature culture speciale) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Loading ValeursFoncieres-2022.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code departement, 1: No Volume, 2: 1er lot, 3: 2eme lot, 4: 3eme lot, 5: Surface Carrez du 3eme lot, 6: Surface Carrez du 4eme lot, 7: Surface Carrez du 5eme lot, 8: Nature culture speciale) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Loading ValeursFoncieres-2023.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code voie, 1: Code departement, 2: No Volume, 3: 1er lot, 4: 2eme lot, 5: 3eme lot, 6: Surface Carrez du 4eme lot, 7: 5eme lot, 8: Surface Carrez du 5eme lot, 9: Nature culture speciale) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Loading ValeursFoncieres-2024.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code departement, 1: No Volume, 2: 1er lot, 3: 2eme lot, 4: 3eme lot, 5: 4eme lot, 6: Surface Carrez du 4eme lot, 7: Surface Carrez du 5eme lot, 8: Nature culture speciale) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Loading ValeursFoncieres-2025-S1.txt...

/Users/xaviervanausloos/projects/ldi_dvf/src/dvf/load.py:41: DtypeWarning: Columns (0: Code departement, 1: No Volume, 2: 1er lot, 3: 2eme lot, 4: 3eme lot, 5: Surface Carrez du 3eme lot, 6: Surface Carrez du 4eme lot, 7: Surface Carrez du 5eme lot) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

Total rows: 20,102,739

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"31234,16",NaN,NaN,NaN,B064,SAINT JULIEN,1560.0,SAINT-JULIEN-SUR-REYSSOUZE,1,367,NaN,A,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,AB,NaN,1192.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250.0,CORVEISSIAT,1,125,NaN,C,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,10092.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B188,A LA PEROUSE,1250.0,CORVEISSIAT,1,125,NaN,C,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,L,NaN,4570.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B079,AUX COMMUNS,1250.0,CORVEISSIAT,1,125,NaN,ZL,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BS,NaN,5750.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"278000,00",NaN,NaN,NaN,B033,EN COMBARNAUD,1250.0,SIMANDRE-SUR-SURAN,1,408,NaN,A,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,BT,NaN,648170.0

In [20]:
# filter df for houses only
df = df[df["Type local"] == "Maison"]
print("Total rows for houses mutations in France: ", len(df))

Total rows for houses mutations in France:  3370550

In [21]:
# Row count and display all columns (no truncation)
print(f"Total rows: {len(df):,}")
print(f"Total columns: {len(df.columns)}")
print("\nAll columns:")
display(df.columns.tolist())

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", 50)
# Preview: first 10 rows with all columns visible
display(df.head(10))

Total rows: 3,370,550
Total columns: 43

All columns:

['Identifiant de document',
 'Reference document',
 '1 Articles CGI',
 '2 Articles CGI',
 '3 Articles CGI',
 '4 Articles CGI',
 '5 Articles CGI',
 'No disposition',
 'Date mutation',
 'Nature mutation',
 'Valeur fonciere',
 'No voie',
 'B/T/Q',
 'Type de voie',
 'Code voie',
 'Voie',
 'Code postal',
 'Commune',
 'Code departement',
 'Code commune',
 'Prefixe de section',
 'Section',
 'No plan',
 'No Volume',
 '1er lot',
 'Surface Carrez du 1er lot',
 '2eme lot',
 'Surface Carrez du 2eme lot',
 '3eme lot',
 'Surface Carrez du 3eme lot',
 '4eme lot',
 'Surface Carrez du 4eme lot',
 '5eme lot',
 'Surface Carrez du 5eme lot',
 'Nombre de lots',
 'Code type local',
 'Type local',
 'Identifiant local',
 'Surface reelle bati',
 'Nombre pieces principales',
 'Nature culture',
 'Nature culture speciale',
 'Surface terrain']

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/07/2020,Vente,"77000,00",347.0,NaN,RTE,0220,DE JALAMONDE,1340.0,BRESSE VALLONS,1,130,NaN,A,1067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,115.0,2.0,S,NaN,2599.0
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2020,Vente,"279000,00",1084.0,NaN,RTE,0079,DE CRANGEAT,1440.0,VIRIAT,1,451,NaN,AB,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,122.0,5.0,S,NaN,1330.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/07/2020,Vente,"177650,00",192.0,NaN,RUE,0348,DE MONTFLEURY,1560.0,SAINT-JEAN-SUR-REYSSOUZE,1,364,NaN,B,554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,80.0,3.0,S,NaN,260.0
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/07/2020,Vente,"169111,00",71.0,NaN,RUE,0605,BRICHEMER,1000.0,BOURG-EN-BRESSE,1,53,NaN,BX,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,86.0,4.0,S,NaN,151.0
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/07/2020,Vente,"190000,00",5062.0,NaN,NaN,B012,EN BOURRAVIER,1250.0,GRAND-CORENT,1,177,NaN,B,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,114.0,4.0,S,NaN,85.0
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/07/2020,Vente,"225000,00",5000.0,NaN,CHE,0074,DE LA GROBE,1160.0,PRIAY,1,314,NaN,D,2672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,108.0,4.0,S,NaN,400.0
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,09/07/2020,Vente,"145590,00",64.0,NaN,CHE,0365,DE LA PERRIERE,1250.0,HAUTECOURT-ROMANECHE,1,184,NaN,AK,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,120.0,4.0,S,NaN,49.0
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10/07/2020,Vente,"217600,00",17.0,NaN,LOT,A001,DU CLOS DES ACACIAS,1340.0,SAINT-DIDIER-D AUSSIAT,1,346,NaN,AI,326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,85.0,4.0,S,NaN,932.0
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/07/2020,Vente,"198000,00",2.0,NaN,RUE,0775,DE CHAMPAGNE,1000.0,BOURG-EN-BRESSE,1,53,NaN,CH,49,NaN,65.0,"117,71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Maison,NaN,117.0,5.0,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/07/2020,Vente,"199500,00",51.0,NaN,ALL,1411,ESPINEUX,1000.0,BOURG-EN-BRESSE,1,53,NaN,BX,351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,101.0,5.0,S,NaN,654.0

In [22]:
# Filter: houses only, commune INSEE 13033 (Ensues)
df = df[(df["Code postal"] == 13820)]
df.head()
print("total rows: ", len(df))

total rows:  305

In [23]:
# Display all columns with their values (no truncation)
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_rows", 100)  # increase if you need more rows
pd.set_option("display.max_colwidth", 40)  # max chars per column (None = no limit)
df

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
217950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/07/2020,Vente,"279200,00",9224.0,NaN,PROM,1035,CHANTEGRIVE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AN,153,NaN,5.0,"45,61",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Maison,NaN,46.0,2.0,NaN,NaN,NaN
218077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/07/2020,Vente,"330000,00",687.0,NaN,AV,2959,DU VALLON DE GRAFFIANE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AS,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,70.0,5.0,AG,NaN,1044.0
218078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/07/2020,Vente,"330000,00",687.0,NaN,AV,2959,DU VALLON DE GRAFFIANE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AS,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,70.0,5.0,S,NaN,500.0
218216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10/07/2020,Vente,"505000,00",5785.0,NaN,NaN,B114,LES TREIZE SAOUQUES,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AD,232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,114.0,4.0,S,NaN,1128.0
219014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/08/2020,Vente,"380000,00",6.0,NaN,CHE,4153,DU VIEUX JAS,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AH,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,90.0,4.0,S,NaN,392.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18879893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/03/2025,Vente,"185000,00",17.0,A,RUE,6660,PASTEUR,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AE,107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,38.0,3.0,S,NaN,41.0
18884058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,24/04/2025,Vente,"825000,00",52.0,NaN,AV,1150,DE LA COTE BLEUE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AE,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,191.0,6.0,S,NaN,1166.0
18885723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,29/04/2025,Vente,"1115020,00",5239.0,NaN,CHE,6652,DU PEBRAIRE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AW,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,100.0,4.0,S,NaN,486.0
18889514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17/06/2025,Vente,"685000,00",8.0,NaN,NaN,B051,LES COLLETS DE LA BONNE ME,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AH,132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,120.0,5.0,S,NaN,988.0
18890443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/06/2025,Vente,"738670,00",5280.0,NaN,NaN,B111,LA REDONNE,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AX,111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,60.0,3.0,S,NaN,170.0

In [24]:
# get min and max date (convert to datetime first; raw format is DD/MM/YYYY so string min/max was wrong)
date_col = "Date mutation"
date_series = pd.to_datetime(df[date_col], format="mixed", dayfirst=True, errors="coerce")
min_date = date_series.min()
max_date = date_series.max()
print(f"Mutation Date range: {min_date} to {max_date}")

Mutation Date range: 2020-07-06 00:00:00 to 2025-06-26 00:00:00

In [25]:
# Merge all rows related to same Code Commune + Prefixe de section + Section
# into a single row with all mutations as a JSON string
import json

# Group by these columns (identify unique properties)
# Note: Prefixe de section can be NaN - fill with empty string for consistent grouping
group_cols = ["Code commune", "Section", "No plan"]

# Columns to keep as house details (take from first row of each group)
house_cols = [
    "Code postal",
    "Commune",
    "Code departement",
    "Code commune",
    "Prefixe de section",
    "Section",
    "No plan",
    "Type local",
    "Surface reelle bati",
    "Surface terrain",
    "Nombre pieces principales",
]

# Group and aggregate
def create_mutations_json(group):
    """Build mutations JSON string from group rows."""
    mutations_list = [
        {row["Date mutation"]: str(row["Valeur fonciere"])}
        for _, row in group.iterrows()
    ]
    return json.dumps(mutations_list, ensure_ascii=False)

# Fill NaN in Prefixe de section with empty string for consistent grouping
# This ensures records with NaN Prefixe de section group together
df_grouping = df.copy()


# Group by Code commune + Prefixe de section + Section
grouped = df_grouping.groupby(group_cols, dropna=False)

# Build result rows
result_rows = []
for (code_commune, prefixe, section), group in grouped:
    house_info = group.iloc[0][house_cols].to_dict()
    house_info["mutations"] = create_mutations_json(group)
    result_rows.append(house_info)

df_grouped = pd.DataFrame(result_rows)
# Order df_grouped by Section
df_grouped = df_grouped.sort_values(by=["Code commune", "Section", "No plan"])

print(f"Original rows: {len(df)}")
print(f"Grouped rows: {len(df_grouped)}")

df_grouped

Original rows: 305
Grouped rows: 253

,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,Type local,Surface reelle bati,Surface terrain,Nombre pieces principales,mutations
0,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AA,19,Maison,80.0,187.0,3.0,"[{""22/07/2021"": ""120000,00""}]"
1,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AA,95,Maison,124.0,447.0,5.0,"[{""07/12/2022"": ""625000,00""}]"
2,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AA,109,Maison,79.0,171.0,4.0,"[{""18/07/2022"": ""435550,00""}]"
3,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AA,111,Maison,82.0,196.0,4.0,"[{""25/09/2023"": ""429500,00""}]"
4,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AA,198,Maison,105.0,337.0,5.0,"[{""20/10/2022"": ""517000,00""}]"
...,...,...,...,...,...,...,...,...,...,...,...,...
248,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AY,104,Maison,104.0,585.0,4.0,"[{""27/01/2023"": ""2505200,00""}]"
249,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AY,121,Maison,79.0,457.0,3.0,"[{""04/05/2021"": ""600000,00""}]"
250,13820.0,ENSUES-LA-REDONNE,13,33,NaN,AY,144,Maison,40.0,NaN,2.0,"[{""26/09/2022"": ""299000,00""}]"
251,13820.0,ENSUES-LA-REDONNE,13,33,NaN,B,820,Maison,90.0,9280.0,3.0,"[{""12/01/2023"": ""315595,38""}, {""12/0..."
252,13820.0,ENSUES-LA-REDONNE,13,33,NaN,B,839,Maison,82.0,360.0,4.0,"[{""22/12/2021"": ""479320,00""}]"

In [26]:
# filter df_grouped for Section = "AT" and No plan = 113
#df_grouped = df_grouped[(df_grouped["Section"] == "AT") & (df_grouped["No plan"] == 113)]
#df_grouped

In [27]:
# Save df_grouped to CSV in data/processed (project root)
from pathlib import Path

# Get project root (where notebooks folder is)
_project_root = Path.cwd() if (Path.cwd() / "src" / "dvf").exists() else Path.cwd().parent

# Ensure data/processed directory exists in project root
output_dir = _project_root / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)

# Save to CSV
output_file = output_dir / "df_grouped_ensues_2020_2025_houses.csv"
df_grouped.to_csv(output_file, index=False)
print(f"Saved to: {output_file.absolute()}")
print(f"File size: {output_file.stat().st_size / 1024:.2f} KB")

Saved to: /Users/xaviervanausloos/projects/ldi_dvf/data/processed/df_grouped_ensues_2020_2025_houses.csv
File size: 26.04 KB